# Generated by Django 4.2.11 on 2024-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("mall", models.CharField(max_length=255)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=255)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secretkey", models.CharField(max_length=255)),
                ("servicekey", models.CharField(max_length=255)),
            ],
        ),
    ]
