# Generated by Django 4.2.13 on 2024-06-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "idx",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("order_mall", models.CharField(max_length=255)),
                ("order_id", models.CharField(max_length=255)),
                ("order_date", models.CharField(max_length=255)),
                ("order_name", models.CharField(max_length=255)),
                (
                    "order_options",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("order_price", models.CharField(max_length=45)),
                (
                    "order_option_price",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("order_count", models.CharField(max_length=45)),
                ("order_person", models.CharField(max_length=45)),
                ("order_address", models.CharField(max_length=45)),
                ("order_phone", models.CharField(max_length=45)),
                ("order_delivery", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
    ]
